version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - app-net
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: organica
      MYSQL_USER: user
      MYSQL_PASSWORD: user

    volumes:
      - ./init:/docker-entrypoint-initdb.d

  backend:
    build: ./Server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      RAZORPAY_KEY: rzp_test_123456789012
      RAZORPAY_SECRET: abcdefghijklmnopqrstuvwx
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/organica
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - app-net

  frontend:
    build: ./Client
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - app-net
networks:
  app-net:
    driver: bridge
